import dependency_manager
print(dependency_manager.PERMISSION_LEVEL_CHOICES)
print(dependency_manager.PERMISSION_LEVEL_RESTRICTED, dependency_manager.PERMISSION_LEVEL_ASK, dependency_manager.PERMISSION_LEVEL_TRUSTED)
